# Debug build config that outputs Docker logs to a GCS file we can read
steps:
  # Attempt to build and capture full output
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x
        docker build \
          --build-arg VITE_API_URL=https://omni-ultra-backend-guzjyv6gfa-ew.a.run.app \
          --build-arg VITE_WS_URL=wss://omni-ultra-backend-guzjyv6gfa-ew.a.run.app \
          -t gcr.io/refined-graph-471712-n9/omni-frontend:debug \
          -f frontend/Dockerfile \
          frontend 2>&1 | tee /workspace/build-log.txt || true
        echo "Build exit code: $?"
        cat /workspace/build-log.txt
    timeout: 1200s

  # Upload the log for inspection
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/build-log.txt', 'gs://refined-graph-471712-n9_cloudbuild/frontend-debug-log.txt']
    timeout: 60s

timeout: 1500s
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
