# Cloud Build Configuration for IIoT Ollama Processing Service
# Builds and deploys the IIoT data processing service to Cloud Run

steps:
  # Build the IIoT Ollama service Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/iiot-ollama-service:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/iiot-ollama-service:latest'
      - '-f'
      - 'Dockerfile.iiot-ollama'
      - '.'
    id: 'build-iiot-service'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/iiot-ollama-service:${SHORT_SHA}'
    id: 'push-iiot-service'
    waitFor: ['build-iiot-service']

  # Deploy IIoT service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'iiot-ollama-processor'
      - '--image=gcr.io/${PROJECT_ID}/iiot-ollama-service:${SHORT_SHA}'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--no-allow-unauthenticated'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--ingress=all'
      - '--port=8080'
      - '--set-env-vars=OLLAMA_URL=${_OLLAMA_URL},OLLAMA_MODEL=llama3,GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
    id: 'deploy-iiot-service'
    waitFor: ['push-iiot-service']

substitutions:
  _REGION: 'europe-west1'
  _OLLAMA_URL: 'http://ollama-ai-inference:11434'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
