steps:
# Build and push the frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/refined-graph-471712-n9/frontend:latest', '.']
  dir: 'app'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/refined-graph-471712-n9/frontend:latest']

# Build and push the backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/refined-graph-471712-n9/backend:latest', '.']
  dir: 'functions'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/refined-graph-471712-n9/backend:latest']

# Apply the ArgoCD applications
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'argocd/app-of-apps.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
