steps:
  # Build the OMNI Professional Dashboard image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.dashboard'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omni-professional-dashboard:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omni-professional-dashboard:latest'
      - '.'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'omni-professional-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/omni-professional-dashboard:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '600'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,ENVIRONMENT=production,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_REGION=europe-west1,ORCHESTRATION_ENABLED=1,OMNI_SYSTEM_CHECKS=false,OMNI_QUIET_CLOUDRUN=true'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/omni-professional-dashboard:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/omni-professional-dashboard:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'