#!/bin/bash

# Setup script for connecting Omni Platform to Grafana Cloud
# This script helps configure Prometheus to forward metrics to Grafana Cloud

set -e

echo "================================================"
echo "Omni Platform - Grafana Cloud Setup"
echo "================================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if prometheus.yml exists
if [ ! -f "prometheus.yml" ]; then
    echo -e "${RED}Error: prometheus.yml not found${NC}"
    echo "Please run this script from the grafana/ directory"
    exit 1
fi

echo "This script will help you configure Grafana Cloud integration."
echo ""
echo "You will need:"
echo "  1. Grafana Cloud account (free tier available at https://grafana.com/auth/sign-up)"
echo "  2. Instance ID (from Grafana Cloud Portal)"
echo "  3. API Key with MetricsPublisher role"
echo ""

read -p "Press Enter to continue or Ctrl+C to cancel..."
echo ""

# Collect Grafana Cloud credentials
echo -e "${YELLOW}Step 1: Get your credentials from Grafana Cloud${NC}"
echo "1. Go to: https://grafana.com/auth/sign-up (if you don't have an account)"
echo "2. Navigate to: Grafana Cloud Portal > Prometheus"
echo "3. Note your Instance ID (e.g., 123456)"
echo "4. Go to: Security > API Keys > Generate API Key"
echo "5. Create key with 'MetricsPublisher' role"
echo ""

read -p "Enter your Grafana Cloud Instance ID: " INSTANCE_ID
read -sp "Enter your Grafana Cloud API Key: " API_KEY
echo ""

read -p "Enter your Grafana Cloud region (e.g., us-central1, eu-west-0): " REGION

read -p "Enter environment name (production/staging/development) [production]: " ENVIRONMENT
ENVIRONMENT=${ENVIRONMENT:-production}

echo ""
echo -e "${YELLOW}Step 2: Updating configuration files${NC}"

# Backup original prometheus.yml
cp prometheus.yml prometheus.yml.backup
echo "✓ Backed up prometheus.yml to prometheus.yml.backup"

# Update prometheus.yml with credentials
sed -i.tmp "s|url: https://prometheus-prod-REGION.grafana.net/api/prom/push|url: https://prometheus-prod-${REGION}.grafana.net/api/prom/push|g" prometheus.yml
sed -i.tmp "s|username: YOUR_GRAFANA_CLOUD_INSTANCE_ID|username: ${INSTANCE_ID}|g" prometheus.yml
sed -i.tmp "s|password: YOUR_GRAFANA_CLOUD_API_KEY|password: ${API_KEY}|g" prometheus.yml
sed -i.tmp "s|replacement: 'production'|replacement: '${ENVIRONMENT}'|g" prometheus.yml
rm -f prometheus.yml.tmp

echo "✓ Updated prometheus.yml with your credentials"

# Create .env file for backend
echo ""
echo -e "${YELLOW}Step 3: Creating .env configuration for backend${NC}"

cat > ../.env.grafana << EOF
# Grafana Cloud Configuration
# Generated by setup-grafana-cloud.sh on $(date)

# Enable Grafana Cloud integration
GRAFANA_CLOUD_ENABLED=true

# Grafana Cloud Prometheus Remote Write endpoint
GRAFANA_CLOUD_REMOTE_WRITE_URL=https://prometheus-prod-${REGION}.grafana.net/api/prom/push

# Grafana Cloud credentials
GRAFANA_CLOUD_USERNAME=${INSTANCE_ID}
GRAFANA_CLOUD_API_KEY=${API_KEY}

# Push interval in seconds (default: 15)
GRAFANA_CLOUD_PUSH_INTERVAL=15
EOF

echo "✓ Created ../.env.grafana configuration file"

echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. Start Prometheus forwarder:"
echo "   cd grafana/"
echo "   docker-compose up -d"
echo ""
echo "2. Load Grafana Cloud config in your backend:"
echo "   export \$(cat ../.env.grafana | xargs)"
echo "   or add to your .env file"
echo ""
echo "3. Restart your backend:"
echo "   uvicorn backend.main:app --reload"
echo ""
echo "4. Verify metrics in Grafana Cloud:"
echo "   - Go to Grafana Cloud Portal"
echo "   - Navigate to Explore > Prometheus"
echo "   - Query: {job=\"omni-backend\"}"
echo ""
echo "5. Import pre-built dashboards:"
echo "   - FastAPI Dashboard: https://grafana.com/grafana/dashboards/16110"
echo "   - Redis Dashboard: https://grafana.com/grafana/dashboards/11835"
echo ""
echo -e "${YELLOW}Note: It may take 1-2 minutes for metrics to appear in Grafana Cloud${NC}"
echo ""
echo "For more help, see: GRAFANA_CLOUD_SETUP.md"
