apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/refined-graph-471712-n9/refined-graph-471712-n9'
    path: k8s/vector-db
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
