import os
import json
import time
from typing import List, Dict, Any, Optional

from fastapi import Body
from pydantic import BaseModel, Field

from .common import build_app, get_async_client


app = build_app("omni-pov")


VALUE_URL = os.getenv("VALUE_URL", "http://omni-value:8000")
DOC_OUTPUT_DIR = os.getenv("DOC_OUTPUT_DIR", "/workspace/docs/auto")
DOC_INDEX_PATH = os.getenv("DOC_INDEX_PATH", "/workspace/docs_index.json")

START_TS = time.time()

def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def update_docs_index(path: str, title: str) -> bool:
    try:
        index = {}
        if os.path.exists(DOC_INDEX_PATH):
            with open(DOC_INDEX_PATH, "r", encoding="utf-8") as fh:
                index = json.load(fh)
        index.setdefault("documents", [])
        existing = {d.get("path"): d for d in index["documents"]}
        existing[path] = {"path": path, "title": title}
        index["documents"] = list(existing.values())
        with open(DOC_INDEX_PATH, "w", encoding="utf-8") as fh:
            json.dump(index, fh, indent=2)
        return True
    except Exception:
        return False


class ChallengeRegistration(BaseModel):
    name: str
    organization: str
    goals: List[str] = Field(default_factory=list)
    category: str = Field("business")


class PoVRequest(BaseModel):
    title: str
    category: str = Field("business")
    description: Optional[str] = None
    metrics: List[Dict[str, Any]] = Field(default_factory=list)
    extra_signals: Dict[str, float] = Field(default_factory=dict)
    guarantee_threshold: float = 0.7


REGISTRY_PATH = os.getenv("POV_REGISTRY_PATH", "/workspace/data/pov_registry.json")


def load_registry() -> Dict[str, Any]:
    try:
        with open(REGISTRY_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"registrations": []}


def save_registry(d: Dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(REGISTRY_PATH), exist_ok=True)
    with open(REGISTRY_PATH, "w", encoding="utf-8") as f:
        json.dump(d, f, indent=2)


@app.post("/challenge/register")
async def challenge_register(reg: ChallengeRegistration):
    db = load_registry()
    db.setdefault("registrations", []).append(reg.model_dump())
    save_registry(db)
    return {"ok": True, "registrations": len(db["registrations"])}


def render_pov(title: str, category: str, score: float, passed: bool, description: Optional[str], details: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append(f"# Proof of Value — {title}")
    lines.append("")
    if description:
        lines.append(description)
        lines.append("")
    lines.append(f"- Category: `{category}`")
    lines.append(f"- Composite score: `{score:.3f}`")
    lines.append(f"- Guarantee: `{'PASSED' if passed else 'PENDING'}`")
    lines.append("")
    lines.append("## Rationale")
    items = details.get("items", []) if isinstance(details, dict) else []
    for it in items:
        lines.append(f"- {it.get('name')}: score={it.get('score')} source={it.get('source')}")
    lines.append("")
    lines.append("---")
    lines.append("Generated by `omni-pov`.")
    return "\n".join(lines)


@app.post("/pov/generate")
async def pov_generate(req: PoVRequest):
    client = get_async_client()
    payload = {
        "title": req.title,
        "category": req.category,
        "description": req.description,
        "metrics": req.metrics,
        "extra_signals": req.extra_signals,
    }
    score = 0.0
    details: Dict[str, Any] = {}
    try:
        r = await client.post(f"{VALUE_URL}/values/qualify", json=payload, timeout=25.0)
        r.raise_for_status()
        js = r.json()
        score = float(js.get("score", 0.0))
        details = js.get("details", {})
    except Exception:
        pass
    passed = score >= req.guarantee_threshold

    md = render_pov(req.title, req.category, score, passed, req.description, details)
    out = None
    updated = False
    try:
        ensure_dir(DOC_OUTPUT_DIR)
        slug = req.title.lower().replace(" ", "-")
        out = os.path.join(DOC_OUTPUT_DIR, f"pov-{slug}.md")
        with open(out, "w", encoding="utf-8") as f:
            f.write(md)
        updated = update_docs_index(os.path.relpath(out, start="/workspace"), f"PoV — {req.title}")
    except Exception:
        pass
    return {"title": req.title, "score": score, "guarantee": passed, "path": out, "index_updated": updated, "markdown": md}


@app.get("/status")
async def status():
    env = {
        "PORT": os.getenv("PORT"),
        "LOG_LEVEL": os.getenv("LOG_LEVEL"),
        "AGENT_MODULE": os.getenv("AGENT_MODULE"),
    }


@app.get("/live")
async def live():
    return {"ok": True, "status": "alive", "agent": "omni-pov"}


@app.get("/ready")
async def ready():
    # Optional dependency check; STRICT_READY enforces failures to mark not ready
    details: Dict[str, Any] = {}
    dep_ok = True
    strict = os.getenv("STRICT_READY", "0").lower() in {"1", "true", "yes", "on"}
    try:
        client = get_async_client()
        r = await client.get(f"{VALUE_URL}/health", timeout=2.0)
        ok_http = (r.status_code == 200)
        details["value_health"] = {"status_code": r.status_code, "ok": ok_http}
        if not ok_http:
            dep_ok = False
    except Exception as e:
        details["value_health_error"] = str(e)
        if strict:
            dep_ok = False
    return {"ok": dep_ok, "agent": "omni-pov", "dependencies": details}
    cfg = {
        "VALUE_URL": VALUE_URL,
        "DOC_OUTPUT_DIR": DOC_OUTPUT_DIR,
        "DOC_INDEX_PATH": DOC_INDEX_PATH,
        "REGISTRY_PATH": REGISTRY_PATH,
    }
    return {
        "ok": True,
        "agent": "omni-pov",
        "env": env,
        "config": cfg,
        "uptime_sec": round(time.time() - START_TS, 3),
    }